Repository betagouv/anssi-portail, pull requests merged in 2025-07, with the labels that each got.

#372 [DIAG] N’affiche pas la modale de sortie en cas de succès
  front/lib-svelte/src/demande-aide-mon-aide-cyber/DemandeAideMAC.svelte
Labels: bug

#374 Autorise les médias en provenance du cellar MSC
  back/src/api/middleware.ts
Labels: enhancement

#379 Apporte quelques retouches à la page statistiques
  front/lib-svelte/src/statistiques/Statistiques.svelte
Labels: bug

#384 Enrichis l'affichage de l'historique
  front/lib-svelte/src/test-maturite/HistoriqueTests.svelte
Labels: enhancement

#387 [HISTORIQUE] Corrige la taille des illustrations des niveaux
  front/lib-svelte/src/test-maturite/CarteTestMaturite.svelte
Labels: bug

#389 Utilise les ressources volumineuses depuis le cellar MSC
  front/_ressources/cyber-enjeux-pro.md
  front/_ressources/cyber-enjeux.md
  front/_ressources/risques-cyber.md
Labels: enhancement

#394 Adapte les libellés du radar de comparaison en mobile
  front/lib-svelte/src/test-maturite/ComparaisonTest.svelte
  front/lib-svelte/src/test-maturite/RadarSessionGroupe.svelte
Labels: enhancement

#396 Supprime la mention « À venir »
  front/index.html
  front/lib-svelte/src/test-maturite/PubliciteMesServicesCyber.svelte
Labels: enhancement

#398 [CORRECTION] Partage le lien vers le test public
  front/lib-svelte/src/test-maturite/BoutonsPartageTest.svelte
Labels: bug

#403 Ajoute les infos d'organisation dans l'événement...
  back/src/api/testMaturite/ressourceResultatsDeTest.ts
  back/src/bus/evenements/testRealise.ts
  back/src/infra/adaptateurJournal.ts
  back/tests/api/testMaturite/ressourceResultatsDeTest.spec.ts
Labels: enhancement

#408 Monte la version de la dépendance lab-anssi
  back/package.json
  back/tests/api/ressourcePageCrisp.spec.ts
  back/tests/mockCmsCrisp.ts
  package-lock.json
Labels: bug, dependencies

#409 Rends réactif les secteurs de l’anneau
  front/lib-svelte/src/test-maturite/GraphiqueAnneau.svelte
Labels: bug

#417 [BUG] Corrige le problème `Axios is not defined`
  front/scripts/sentry.js
Labels: bug

#419 [COMPARAISON] Visuel comparaison pas de résultats
  front/_layouts/defaut.html
  front/lib-svelte/src/test-maturite/ComparaisonTest.svelte
Labels: enhancement
