Repository betagouv/anssi-portail, pull requests merged in 2025-04, with the labels that each got.

#246 Supprime le layout favoris qui n'est plus utile
  front/_layouts/favoris.html
  front/assets/styles/favoris.scss
  front/favoris-partages.html
  front/favoris.html
  front/lib-svelte/src/favoris/FavorisPartages.svelte
Labels: enhancement

#250 Corrige visuellement le comportement du bouton favori
  front/lib-svelte/src/favoris/BoutonFavori.svelte
Labels: bug

#251 [SOIN] Corrige une erreur lint
  front/lib-svelte/src/favoris/BoutonFavori.svelte
Labels: enhancement

#268 [CORRECTION] Corrige les types Axios au niveau de lib-svelte
  front/lib-svelte/package.json
  package-lock.json
Labels: dependencies

#274 Corrige l’encodage des caractères envoyés à Brevo
  back/package.json
  back/src/infra/adaptateurEmailBrevo.ts
  package-lock.json
Labels: bug

#281 Ajuste les rythmes de cadencement
  back/src/admin/consoleAdministration.ts
  back/src/infra/entrepotUtilisateurMPAPostgres.ts
Labels: bug

#288 [CORRECTION] Corrige l'inscription qui été bloqué lors de la soumission du formulaire
  back/src/infra/utilisateurBDD.ts
  back/src/metier/utilisateur.ts
Labels: bug

#292 Supprime le fond gris sur le fil d'ariane dans les pages services
  front/assets/styles/service.scss
Labels: enhancement

#296 Ajoute des couleurs au `concurrently`
  package.json
Labels: enhancement

#297 Ajoute une vérification typescript lors des tests back
  back/package.json
Labels: enhancement

#301 [CORRECTION] Ajoute les informations PSSI sur la page de sécurité
  front/_layouts/defaut.html
Labels: bug
