Repository betagouv/anssi-portail, pull requests merged in 2025-03, with the labels that each got.

#123 Ajoute un fichier de license Apache 2.0
  LICENSE
Labels: enhancement

#124 Utilise les variables `--build-arg` passées dans le Dockerfile
  Dockerfile
  README.md
Labels: bug, enhancement

#125 [CORRECTION] Prend en compte les variables d'environnement vide
  front/_layouts/defaut.html
Labels: bug

#129 Corrige le formatage du script de lancement de Matomo
  front/_includes/script-matomo.html
Labels: bug

#136 Corrige le script pour lancer la migration knex dans le déploiement
  package.json
Labels: bug

#137 Ajoute l’application dans docker-compose
  .env.template
  Dockerfile
  README.md
  docker-compose.yml
  package.json
Labels: bug

#131 [CORRECTION] Applique le font "Marianne" sur les "select"
  front/assets/styles/site.scss
Labels: bug

#143 [CORRECTION] Corrige le lancement des migrations en local
  package.json
Labels: bug

#147 [SOIN] Utilise la configuration de test du serveur
  back/tests/api/oidc/ressourceApresAuthentificationOIDC.spec.ts
  back/tests/api/oidc/ressourceConnexionOIDC.spec.ts
  back/tests/api/oidc/ressourceDeconnexionOIDC.spec.ts
  back/tests/api/ressourceAnnuaireDepartements.spec.ts
  back/tests/api/ressourceAnnuaireOrganisations.spec.ts
  back/tests/api/ressourcePagesJekyll.spec.ts
Labels: enhancement

#155 Redirige le CTA de la page d’accueil vers la page de connexion
  front/index.html
Labels: enhancement

#166 Ajoute une entrée au référentiel des régions
  back/src/metier/referentielRegions.ts
Labels: enhancement

#167 Ajoute un faux adaptateur MonProfilAnssi
  back/src/infra/adaptateurProfilAnssi.ts
  back/src/infra/adaptateurProfilAnssiVide.ts
Labels: enhancement

#171 Corrige l’envoi du statut lors de la vérification JWT
  back/src/api/middleware.ts
  back/tests/api/middleware.spec.ts
Labels: bug

#182 Redirige l'utilisateur vers la page de connexion
  front/lib-svelte/src/test-maturite/PubliciteMesServicesCyber.svelte
Labels: enhancement

#181 Redirige vers la page du test de maturité
  front/lib-svelte/src/test-maturite/MaturiteUtilisateur.svelte
Labels: enhancement

#180 Ajoute la navigation en mode "connecté"
  front/lib-svelte/src/navigation/NavigationBureau.svelte
  front/lib-svelte/src/navigation/NavigationMobile.svelte
Labels: enhancement

#184 Retire le tag "Bêta" du header
  front/_includes/header.html
  front/assets/styles/site.scss
Labels: enhancement

#199 Corrige la typologie du `Label ExpertCyber`
  front/_data/catalogue.yml
  front/_data/parcours-debuter.yml
Labels: bug

#201 [CORRECTION] Ne réactive le bouton que si l'envoi du formulaire a échoué
  front/lib-svelte/src/creation-compte/CreationCompte.svelte
Labels: bug

#213 Corrige la hauteur de la carte 17cyber
  front/_services/diagnostic-17cyber.md
Labels: bug

#216 [MATURITE] Affiche des onglets
  front/assets/styles/test-maturite.scss
  front/lib-svelte/src/test-maturite/ResultatsTestMaturite.svelte
  front/lib-svelte/src/ui/ConteneurOnglets.svelte
  front/lib-svelte/src/ui/Onglet.svelte
Labels: enhancement

#219 Différencie l'utilisateur connecté et non connecté sur les favoris partagés
  front/lib-svelte/src/favoris/FavorisPartages.svelte
Labels: enhancement

#223 Rassemble les contacts selon leur caractère régional ou national
  front/lib-svelte/src/contacts/Contacts.svelte
Labels: enhancement

#237 Supprime les espaces invisibles dans la recherche
  front/lib-svelte/src/catalogue/stores/rechercheTextuelle.store.ts
Labels: bug

#236 [CORRECTION] Externalise les images du bouton ProConnect
  front/assets/images/pro_connect.svg
  front/assets/images/pro_connect_hover.svg
  front/assets/styles/connexion.scss
Labels: bug
